<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LogoImage</name>
   <tag></tag>
   <elementGuidId>2d460404-d84b-49da-a3cd-e570a1c25ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imagetrgt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
